apiVersion: serving.knative.dev/v1
kind: Route
metadata:
  name: demo-api-route
  namespace: default
spec:
  traffic:
    - revisionName: demo-api-00002
      percent: 100 # All traffic goes to this revision
      tag: v2
    - revisionName: demo-api-00003
      percent: 0 # 0% of traffic routed to the second revision
      tag: v3 # A named route
